# Generated by Django 5.2.1 on 2025-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('ROUTE', 'Problème de route'), ('ELECTRICITE', 'Coupure électrique'), ('DECHETS', 'Dépôt de déchets'), ('AUTRE', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('adresse', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='signalements/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
